config/routes.rb
Amazon::Application.routes.draw do
  devise_for :users
  resources :dashboard

  resources :credit_cards

  resources :countries

  resources :addresses

  resources :order_items

  resources :orders

  resources :customers

  resources :ratings

  resources :authors

  resources :categories

  resources :books

  root 'home#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :country

  validates_presence_of :address, :zipcode, :city, :phone

  def to_s
   "#{address}, #{city}, #{zipcode}, #{phone}"

  end

end

app/models/author.rb
class Author < ActiveRecord::Base
   validates :first_name, :last_name, presence: true
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/country.rb
class Country < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
end

app/models/credit_card.rb
class CreditCard < ActiveRecord::Base
   belongs_to :order
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  validates_numericality_of :quantity, :price
  belongs_to :product
  belongs_to :order

  before_save :count_price
  after_destroy :back_product_to_stock

  def count_price
    self.price = (product.price * quantity).to_f
  end
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :product
  belongs_to :customer

  validates :rating, presence: true, numericality: {only_integer: true}, :inclusion => {:in => 1..10}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  before_action :set_credit_card, only: [:show, :edit, :update, :destroy]

  # GET /credit_cards
  # GET /credit_cards.json
  def index
    @credit_cards = CreditCard.all
  end

  # GET /credit_cards/1
  # GET /credit_cards/1.json
  def show
  end

  # GET /credit_cards/new
  def new
    @credit_card = CreditCard.new
  end

  # GET /credit_cards/1/edit
  def edit
  end

  # POST /credit_cards
  # POST /credit_cards.json
  def create
    @credit_card = CreditCard.new(credit_card_params)

    respond_to do |format|
      if @credit_card.save
        format.html { redirect_to @credit_card, notice: 'Credit card was successfully created.' }
        format.json { render action: 'show', status: :created, location: @credit_card }
      else
        format.html { render action: 'new' }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credit_cards/1
  # PATCH/PUT /credit_cards/1.json
  def update
    respond_to do |format|
      if @credit_card.update(credit_card_params)
        format.html { redirect_to @credit_card, notice: 'Credit card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credit_cards/1
  # DELETE /credit_cards/1.json
  def destroy
    @credit_card.destroy
    respond_to do |format|
      format.html { redirect_to credit_cards_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit_card
      @credit_card = CreditCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def credit_card_params
      params.require(:credit_card).permit(:number, :cvv, :expiration_month, :expiration_year, :firstname, :last, :name)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/credit_cards/_form.html.erb
<%= form_for(@credit_card) do |f| %>
  <% if @credit_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@credit_card.errors.count, "error") %> prohibited this credit_card from being saved:</h2>

      <ul>
      <% @credit_card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :cvv %><br>
    <%= f.text_field :cvv %>
  </div>
  <div class="field">
    <%= f.label :expiration_month %><br>
    <%= f.text_field :expiration_month %>
  </div>
  <div class="field">
    <%= f.label :expiration_year %><br>
    <%= f.text_field :expiration_year %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :last %><br>
    <%= f.text_field :last %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/credit_cards/edit.html.erb
<h1>Editing credit_card</h1>

<%= render 'form' %>

<%= link_to 'Show', @credit_card %> |
<%= link_to 'Back', credit_cards_path %>

app/views/credit_cards/index.html.erb
<h1>Listing credit_cards</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Cvv</th>
      <th>Expiration month</th>
      <th>Expiration year</th>
      <th>Firstname</th>
      <th>Last</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @credit_cards.each do |credit_card| %>
      <tr>
        <td><%= credit_card.number %></td>
        <td><%= credit_card.cvv %></td>
        <td><%= credit_card.expiration_month %></td>
        <td><%= credit_card.expiration_year %></td>
        <td><%= credit_card.firstname %></td>
        <td><%= credit_card.last %></td>
        <td><%= credit_card.name %></td>
        <td><%= link_to 'Show', credit_card %></td>
        <td><%= link_to 'Edit', edit_credit_card_path(credit_card) %></td>
        <td><%= link_to 'Destroy', credit_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Credit card', new_credit_card_path %>

app/views/credit_cards/new.html.erb
<h1>New credit_card</h1>

<%= render 'form' %>

<%= link_to 'Back', credit_cards_path %>

app/views/credit_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @credit_card.number %>
</p>

<p>
  <strong>Cvv:</strong>
  <%= @credit_card.cvv %>
</p>

<p>
  <strong>Expiration month:</strong>
  <%= @credit_card.expiration_month %>
</p>

<p>
  <strong>Expiration year:</strong>
  <%= @credit_card.expiration_year %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @credit_card.firstname %>
</p>

<p>
  <strong>Last:</strong>
  <%= @credit_card.last %>
</p>

<p>
  <strong>Name:</strong>
  <%= @credit_card.name %>
</p>

<%= link_to 'Edit', edit_credit_card_path(@credit_card) %> |
<%= link_to 'Back', credit_cards_path %>